# config for model trace analysis

defaults:
  - arch: trm_trace
  - _self_

eval_loss:
  name: losses.eval_loss@EvalLossHead

hydra:
  output_subdir: null

# Model checkpoint path
load_checkpoint: ""

# Data path
data_paths: ['data/arc-aug-1000']
data_paths_test: []

evaluators:
  - name: arc@ARC

# Hyperparams
global_batch_size: 128

# Inference parameters
seed: 0

# Z analysis
z_analysis_max_samples: 50000
z_analysis_max_samples_pca: 256
z_analysis_pca_components: 10
rec_max_correct: 50
rec_max_incorrect: 50